### ISSUE TITLE
ReferenceError: msg is not defined

### ISSUE THREAD

**Issue by jstart** [hubot-scripts/hubot-ghe#2]
[Fri Oct 16 2015 14:30:47 GMT-0700 (PDT)] ERROR Unable to load /Users/release-svc/alfred/node_modules/hubot-ghe/src/ghe: ReferenceError: msg is not defined
  at module.exports (/Users/release-svc/alfred/node_modules/hubot-ghe/src/ghe.coffee:33:5, <js>:10:7)
  at Robot.loadFile (/Users/release-svc/alfred/node_modules/hubot/src/robot.coffee:340:11, <js>:217:13)
  at /Users/release-svc/alfred/node_modules/hubot-ghe/index.coffee:12:11, <js>:26:33
  at FSReqWrap.cb [as oncomplete](fs.js:212:19)

Is this a problem with my setup, or a real bug?

**Comment by mgriffin** [comment]
This is a little bit of both.

The :bug: is that I hadn't set up error logging correctly. I'm going to open a PR to fix that in a few minutes.

The problem with your setup is that you haven't defined the `HUBOT_GHE_TOKEN` environment variable, which is needed to authenticate to your GitHub Enterprise appliance.

**Comment by jstart** [comment]
Awesome thanks!
